### ISSUE TITLE
TRE bug and recursive_iterator improvements

### ISSUE THREAD

**Issue by pchampin** [evhub/coconut#264]
The following function aims to partition an iterator (wrt a given pivot) in a single pass:
```python
def partition(items, pivot, lprefix=[], rprefix=[]):
    case items:
        match [head]::tail:
            if head < pivot:
                return partition(tail, pivot, [head]::lprefix, rprefix)
            else:
                return partition(tail, pivot, lprefix, [head]::rprefix)
        match []::_:
            return lprefix, rprefix
```
It fails with the following exception:
```
coconut.exceptions.CoconutSyntaxError: variable names cannot start with reserved prefix _coconut (line 1)
  return partition(tail, pivot, _coconut.itertools.chain.from_iterable((_coconut_lazy_item() for _coconut_lazy_item in (lambda: [head], lambda: lprefix))), rprefix)
                                ^
```

Note that producing lists (with ``+``) instead of iterators (with ``::``) in the first two return statements "solves" the problem:
```python
def partition(items, pivot, lprefix=[], rprefix=[]):
    case items:
        match [head]::tail:
            if head < pivot:
                return partition(tail, pivot, [head]+lprefix, rprefix)
            else:
                return partition(tail, pivot, lprefix, [head]+rprefix)
        match []::_:
            return lprefix, rprefix
```

**Comment by evhub** [comment]
Postmortem for future reference: The issue here was that TRE was using function_call instead of parens, which meant it was trying to parse the function arguments when it shouldn't have been. Ideally, this would have triggered a complain, not an error, but the proper complain catching logic wasn't set up in the specific location where the error was occurring. Both of these issues have been fixed and a regression test for the main issue has been added.

**Comment by pchampin** [comment]
Sorry, but after installing ``coconut-develop`` with 248a59a included,
I still have a problem:
```python
@recursive_iterator
def partition(items, pivot, lprefix=[], rprefix=[]):
    case items:
        match [head]::tail:
            if head < pivot:
                return partition(tail, pivot, [head]::lprefix, rprefix)
            else:
                return partition(tail, pivot, lprefix, [head]::rprefix)
        match []::_:
            return lprefix, rprefix

expand_all = (x) -> [list(i) for i in x]
partition([], 5) |> expand_all |> print
partition([2,7,0,7,7,4], 5) |>  expand_all |> print
partition([2,7,0,7,7,4], 3) |>  expand_all |> print
```
gives the following output
```
[[], []]
Traceback (most recent call last):
  File "/tmp/test.py", line 416, in recursive_iterator_func
    to_tee = tee_store[hashable_args_kwargs]
KeyError: b'\x80\x04\x95\x19\x00\x00\x00\x00\x00\x00\x00]\x94(K\x02K\x07K\x00K\x07K\x07K\x04eK\x05\x86\x94}\x94\x86\x94.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/test.py", line 540, in <module>
    (print)((expand_all)(partition([2, 7, 0, 7, 7, 4], 5)))
  File "/tmp/test.py", line 418, in recursive_iterator_func
    to_tee = func(*args, **kwargs)
  File "/tmp/test.py", line 150, in tail_call_optimized_func
    return call_func(*args, **kwargs)  # pass --no-tco to clean up your traceback
  File "/tmp/test.py", line 414, in recursive_iterator_func
    hashable_args_kwargs = _coconut.pickle.dumps((args, kwargs), _coconut.pickle.HIGHEST_PROTOCOL)
TypeError: can't pickle generator objects
```
Note that the function succeeds when passed with an empty iterable, but fails with a non-empty one.

**Comment by evhub** [comment]
@pchampin Interesting! So, currently, this is intended behavior: the way `@recursive_iterator` fixes the segfault issue relies on pickling the given function arguments (see \#4 [here](http://coconut.readthedocs.io/en/master/DOCS.html#recursive-iterator)). However, I think this is a totally valid use case for why that might be too restrictive of a condition on `@recursive_iterator`, so I'll see if I can find a way to fix the segfault without relying on pickling.

**Comment by evhub** [comment]
@pchampin I put out a new version of `coconut-develop` with a modified `@recursive_iterator` that should fix your issue. I think it's good, but I'm not 100% confident in the new version's reliability yet, so it'd be great if you could test it out!

**Comment by pchampin** [comment]
I tried some more examples in the same spirit (see attached file), and they all seem to work. Congrats :)
[test.coco](https://github.com/evhub/coconut/files/1074567/test.txt)

**Comment by evhub** [comment]
@pchampin Great, good to hear it's working for you!

**Comment by pchampin** [comment]
Sorry to bother you with this again, but I ran into another edge-case. I was trying to implement my own version of reduce (just for the sake of learning). This is how I first tried:
```python
def myreduce(func, items):
    match [first]::tail1 in items:
        match [second]::tail2 in tail1:
            return myreduce(func, [func(first, second)]::tail2)
        else:
            return first
```
but then I got the segfault bug :-(

I solved the problem like this (with your latest patches on ``recursive_iterator``):
```python
@recursive_iterator
def _myreduce(func, items):
    match [first]::tail1 in items:
        match [second]::tail2 in tail1:
            return _myreduce(func, [func(first, second)]::tail2)
        else:
            return [first]

def myreduce(func, items) = _myreduce(func, items)[0]
```
Note that the intermediate ``_myreduce`` function artificially returns a one-element list, in order to satisfy the requirement that ``recursive_iterator``s must return an iterable.

I think the issue here is that ``recursive_iterator`` plays two distinct roles:
* optimizing recursive iterators, and
* fixing the segfault bug.

Wouldn't it be possible to have a separate decorator just for fixing the segfault bug in recursive functions that do not return an iterator?

**Comment by evhub** [comment]
@pchampin Interesting! I've never seen the segfault bug show up in that context before. It definitely does seem like a separate decorator for resolving the bug for non-iterator functions is necessary (probably something like `@memoize`, since `@recursive_iterator` is effectively iterator memoization behind the scenes). This definitely deserves its own issue--either you can raise another issue about this if you want, or I'll take care of it when I get back from work today.
