### ISSUE TITLE
Coconut Kernel failing with Jupyter

### ISSUE THREAD

**Issue by mlarocca** [evhub/coconut#337]
A `WindowsError` (file not found) is raised both when running `coconut --jupyter console` and  `coconut --jupyter notebook`

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\coconut\command\command.py", line 268, in handling_exceptions
    yield
  File "C:\ProgramData\Anaconda2\lib\site-packages\coconut\command\command.py", line 118, in cmd
    self.use_args(parsed_args, interact, original_args=args)
  File "C:\ProgramData\Anaconda2\lib\site-packages\coconut\command\command.py", line 239, in use_args
    self.start_jupyter(args.jupyter)
  File "C:\ProgramData\Anaconda2\lib\site-packages\coconut\command\command.py", line 621, in start_jupyter
    install_func(["python" + ver, "-m", "coconut.main", "--version"])
  File "C:\ProgramData\Anaconda2\lib\site-packages\coconut\command\util.py", line 242, in run_cmd
    stdout, stderr, _ = call_output(cmd, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\coconut\command\util.py", line 211, in call_output
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\ProgramData\Anaconda2\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] Unable to find file
(you should report this at https://github.com/evhub/coconut/issues/new)
Coconut: Exiting due to WindowsError.

``

**Comment by auscompgeek** [comment]
Heh. Looks like you don't have a `python{ver}` executable, which makes sense on Windows.

Why doesn't coconut use `sys.executable`?

**Comment by mlarocca** [comment]
Thanks!
Yeah, I was pretty sure it was the same issue as #281 :D 
I had tried, though, to install the `develop` version, and I still got the same failure :'(

**Comment by evhub** [comment]
@mlarocca Hmmm... that seems to imply you don't have a `python` executable either. Can you show me the output of `coconut --verbose --jupyter console`?

**Comment by mlarocca** [comment]
Sure:

```
Using Python pyparsing v2.2.0.
Parsed args: Namespace(argv=None, code=None, dest=None, display=False, documentation=False, force=False, interact=False, jobs=None, jupyter=[u'console'], keep_lines=False, line_numbers=False, minify=False, mypy=None, no_tco=False, no_write=False, package=False, quiet=False, recursion_limit=None, run=False, source=None, standalone=False, strict=False, style=None, target=None, trace=False, tutorial=False, verbose=True, watch=False)
Compiler args: {'keep_lines': False, 'minify': False, 'target': u'', 'line_numbers': False, 'no_tco': False, 'strict': False}
> jupyter --version
4.2.1
> jupyter kernelspec list
> python2 -m coconut.main --version
Traceback (most recent call last):
  File "c:\programdata\anaconda2\lib\site-packages\coconut\command\command.py", line 268, in handling_exceptions
    yield
  File "c:\programdata\anaconda2\lib\site-packages\coconut\command\command.py", line 118, in cmd
    self.use_args(parsed_args, interact, original_args=args)
  File "c:\programdata\anaconda2\lib\site-packages\coconut\command\command.py", line 239, in use_args
    self.start_jupyter(args.jupyter)
  File "c:\programdata\anaconda2\lib\site-packages\coconut\command\command.py", line 622, in start_jupyter
    install_func(["python" + ver, "-m", "coconut.main", "--version"])
  File "c:\programdata\anaconda2\lib\site-packages\coconut\command\util.py", line 246, in run_cmd
    return subprocess.check_call(cmd, **kwargs)
  File "c:\programdata\anaconda2\lib\subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\programdata\anaconda2\lib\subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "c:\programdata\anaconda2\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "c:\programdata\anaconda2\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] File could not be found
(you should report this at https://github.com/evhub/coconut/issues/new)
Coconut: Exiting due to WindowsError.
```

It seems so, but that's strange, because of course I do have Python (2) installed with Anaconda, working both on Git bash and Command prompt.

```
which python
/c/ProgramData/Anaconda2/python
```

Thanks again!

**Comment by evhub** [comment]
@mlarocca Ah, I see. It looks like the problem is that Coconut's expecting a `CalledProcessError`, but it's getting a `WindowsError` instead. This has now been fixed on `coconut-develop`, so if you `pip install --upgrade coconut-develop`, it should work now!

**Comment by mlarocca** [comment]
Thanks @evhub !
Unfortunately I tried with the latest coconut-develop, as you suggested, but I still get the same error. (I also tried uninstalling and re-installing, just in case, but no luck).
I get the same error on all Windows 10 machines on which I tried it. I haven't had a chance to test this on  a different version of Windows.

**Comment by evhub** [comment]
@mlarocca Are you sure you're using `v1.3.0-post_dev5`? Sometimes it can take a while for Travis to publish new develop versions.

**Comment by mlarocca** [comment]
@evhub you are right, it was `v1.3.0-post_dev4`! 
Now I upgraded successfully and the problem is solved.
Awesome!
